import {
  AiOutlineArrowRight,
  AiFillSetting,
  AiOutlineLogout,
  AiOutlineBell,
  AiOutlineMessage,
  AiOutlineArrowUp,
  AiOutlineEye,
  AiOutlineShoppingCart,
  AiOutlineShopping,
  AiOutlineNotification,
  AiFillPlusCircle,
  AiOutlinePlus,
  AiOutlineDelete,
  AiOutlineCopy,
  AiFillTag,
  AiFillTags,
  AiOutlineSave,
  AiOutlineDoubleRight,
  AiOutlineDoubleLeft,
  AiOutlineDashboard,
  AiOutlineUser,
  AiOutlineBulb,
  AiFillCloseCircle,
  AiOutlineSearch,
  AiOutlineTransaction,
  AiOutlineExclamationCircle,
} from "react-icons/ai";
import {
  BsChevronLeft,
  BsChevronRight,
  BsFillEyeSlashFill,
  BsFileEarmarkPlus,
  BsLink45Deg,
  BsPencil,
  BsPersonWorkspace,
  BsChevronDown,
  BsChevronUp,
  BsCollection,
  BsDatabaseFill,
  BsFillInfoCircleFill,
  BsViewStacked,
  BsFillPlusCircleFill,
} from "react-icons/bs";
import {
  BiSolidUser,
  BiSolidContact,
  BiMenu,
  BiSolidCreditCard,
  BiSolidCopyAlt,
  BiLineChart,
  BiLineChartDown,
  BiEdit,
  BiCalendar,
  BiWallet,
  BiCheckDouble,
  BiBell,
  BiMessageSquareEdit,
  BiSolidMessageSquareEdit,
} from "react-icons/bi";
import { FaUsers, FaBell, FaPlusCircle, FaCircle } from "react-icons/fa";
import { CgSwap, CgArrowsShrinkV, CgShoppingBag } from "react-icons/cg";
import {
  HiArrowsRightLeft,
  HiReceiptRefund,
  HiDocumentText,
  HiMinusCircle,
} from "react-icons/hi2";
import {
  MdManageAccounts,
  MdSpaceDashboard,
  MdSubscriptions,
  MdCancel,
  MdViewStream,
  MdOutlineShoppingCartCheckout,
  MdPreview,
  MdPriceChange,
  MdSupervisorAccount,
  MdClass,
  MdDelete,
} from "react-icons/md";
import {
  FaClockRotateLeft,
  FaCalendarDays,
  FaBoxesStacked,
  FaPlus,
  FaFileInvoiceDollar,
  FaHandshakeSimple,
  FaCircleMinus,
} from "react-icons/fa6";

import { FcGoogle } from "react-icons/fc";
import { FiAlignLeft, FiHome } from "react-icons/fi";
import {
  PiUserList,
  PiArrowBendLeftUpBold,
  PiClipboardTextBold,
} from "react-icons/pi";
import { TiThMenu } from "react-icons/ti";

import { RiHandCoinFill, RiCoupon2Fill, RiCouponLine } from "react-icons/ri";

import {
  IoMdSettings,
  IoMdArrowBack,
  IoMdArrowForward,
  IoMdClose,
} from "react-icons/io";

import { SlPlus } from "react-icons/sl";

import { CiCirclePlus } from "react-icons/ci";
import { RxCross2, RxDashboard } from "react-icons/rx";

import { BiDesktop } from "react-icons/bi";

import { TfiMenuAlt } from "react-icons/tfi";

import { TbCheck } from "react-icons/tb";
import { CiSearch } from "react-icons/ci";

export {
  FaCircleMinus,
  HiMinusCircle,
  BsFillPlusCircleFill,
  MdDelete,
  BiSolidMessageSquareEdit,
  MdClass,
  CiSearch,
  IoMdClose,
  BiMessageSquareEdit,
  TbCheck,
  TfiMenuAlt,
  BiBell,
  IoMdArrowForward,
  IoMdArrowBack,
  FiHome,
  BiCheckDouble,
  BiWallet,
  AiOutlineExclamationCircle,
  BiCalendar,
  PiClipboardTextBold,
  RiCouponLine,
  BsViewStacked,
  RxDashboard,
  BiDesktop,
  BiEdit,
  CgShoppingBag,
  FaCircle,
  RxCross2,
  PiArrowBendLeftUpBold,
  FaPlusCircle,
  CiCirclePlus,
  IoMdSettings,
  BiLineChart,
  BiLineChartDown,
  BiSolidCopyAlt,
  RiCoupon2Fill,
  SlPlus,
  FaHandshakeSimple,
  BiSolidCreditCard,
  HiDocumentText,
  FaFileInvoiceDollar,
  FaPlus,
  MdPriceChange,
  MdPreview,
  BsFillInfoCircleFill,
  MdOutlineShoppingCartCheckout,
  MdViewStream,
  RiHandCoinFill,
  HiReceiptRefund,
  FaBoxesStacked,
  MdSupervisorAccount,
  MdCancel,
  AiOutlineTransaction,
  MdSubscriptions,
  FaCalendarDays,
  BsDatabaseFill,
  TiThMenu,
  FaBell,
  MdSpaceDashboard,
  PiUserList,
  FiAlignLeft,
  FcGoogle,
  AiOutlineArrowRight,
  BsChevronLeft,
  BsChevronRight,
  BiSolidUser,
  BiSolidContact,
  AiFillSetting,
  AiOutlineLogout,
  AiOutlineBell,
  AiOutlineMessage,
  BiMenu,
  AiOutlineArrowUp,
  AiOutlineEye,
  AiOutlineShoppingCart,
  AiOutlineShopping,
  FaUsers,
  AiOutlineNotification,
  AiFillPlusCircle,
  AiOutlinePlus,
  AiOutlineDelete,
  AiOutlineCopy,
  BsFillEyeSlashFill,
  BsFileEarmarkPlus,
  BsLink45Deg,
  BsPencil,
  CgSwap,
  HiArrowsRightLeft,
  AiFillTag,
  AiFillTags,
  AiOutlineSave,
  AiOutlineDoubleRight,
  AiOutlineDoubleLeft,
  AiOutlineDashboard,
  AiOutlineUser,
  BsPersonWorkspace,
  BsChevronDown,
  MdManageAccounts,
  AiOutlineBulb,
  BsCollection,
  AiFillCloseCircle,
  AiOutlineSearch,
  FaClockRotateLeft,
  BsChevronUp,
};
